version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Print CIRCLE_SHA1
          command: echo "CIRCLE_SHA1: $CIRCLE_SHA1"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Docker Image
          command: |
            TAG=$(echo $CIRCLE_SHA1 | tr '[:upper:]' '[:lower:]')
            docker build -t $DOCKER_LOGIN/$APP_NAME:$TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $DOCKER_LOGIN/$APP_NAME:$TAG


workflows:
  deploy:
    jobs:
      - build:
          context: docker-context
