version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_LOGIN/$APP_NAME:$CIRCLE_SHA1 .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $DOCKER_LOGIN/$APP_NAME:$CIRCLE_SHA1

workflows:
  deploy:
    jobs:
      - build:
          context: docker-context
